export const BOOK = {
  BOOK_GET_LIST: "BOOK/GET_LIST",
  BOOK_GET_LIST_SUCCESS: "BOOK/GET_LIST_SUCCESS",

  BOOK_CREATE: "BOOK/CREATE",
  CHANGE_PAGE: "BOOK/CHANGE_PAGE",
  DELETE_BOOK: "BOOK/DELETE",
  EDIT_BOOK: "BOOK/EDIT_BOOK"
};
